### ISSUE TITLE
Example Config would be needed

### ISSUE THREAD

**Issue by Hornochs** [thannaske/cmk-teamspeak#1]
Heyho,

I'm trying to setup a checkMK Server with this TeamSpeak Plugin. But I have no Idea how the teamspeak3.cfg should look. Would it be possible to help me with that?

Thanks!

Cheers,

Hornochs

**Comment by thannaske** [comment]
Hey, sorry that I didn't provide any configuration example. Here you go:

```
[serverquery]
address = "127.0.0.1"
user = serveradmin
password = pass
```

Hope that helps.

**Comment by Hornochs** [comment]
Heyho,

thanks! That helped a lot :)

Cheers,
Hornochs
